// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHgGpMbWpP8K-XezKB7Bfxz5DLb8V9T4Y',
    appId: '1:214402586585:android:38cd43138619e675f5abc8',
    messagingSenderId: '214402586585',
    projectId: 'geo-chat-f40f8',
    storageBucket: 'geo-chat-f40f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1PF49pRc5OhfaNroBb2Akix8hiOs2IkI',
    appId: '1:214402586585:ios:c96b3d3805492c44f5abc8',
    messagingSenderId: '214402586585',
    projectId: 'geo-chat-f40f8',
    storageBucket: 'geo-chat-f40f8.firebasestorage.app',
    androidClientId: '214402586585-7ctebt9nace4elnc08ddp8abdk7vfcem.apps.googleusercontent.com',
    iosClientId: '214402586585-vhqk88sd348qmjumn6uv3afaoj0v1gpr.apps.googleusercontent.com',
    iosBundleId: 'com.geochat.chat',
  );

}